name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pytest dvc[gcs]
    
    - name: Authenticate to Google Cloud
      run: |
        echo '${{ secrets.GCS_CREDENTIALS }}' > ${HOME}/gcs-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcs-credentials.json
    
    - name: Pull data from DVC
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcs-credentials.json
      run: |
        echo '${{ secrets.GCS_CREDENTIALS }}' > gcs-credentials.json
        dvc pull
    
    - name: Run tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q | tee report.txt
    
    - name: Setup CML
      if: github.event_name == 'pull_request'
      uses: iterative/setup-cml@v2
    
    - name: Create CML report
      if: github.event_name == 'pull_request'
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Test Results" > report.md
        cat report.txt >> report.md
        cml comment create report.md
